// mediasfu_reactjs/src/components/MediaSFUHandler.tsx
import React, { useRef } from "react";
import {
  CreateMediaSFURoomOptions,
  JoinMediaSFURoomOptions,
  MediasfuGeneric,
  PreJoinPage,
} from "mediasfu-reactjs";

export interface MediaSFUHandlerProps {
  action: "create" | "join";
  duration?: number;
  capacity?: number;
  name: string;
  meetingID?: string; // Optional for create, required for join
  sourceParameters: Record<string, any>;
  updateSourceParameters: (params: Record<string, any>) => void;
}

const MediaSFUHandler: React.FC<MediaSFUHandlerProps> = ({
  action,
  duration,
  capacity,
  name,
  meetingID,
  sourceParameters,
  updateSourceParameters,
}) => {
  const localLink = useRef<string | undefined>("http://localhost:3000");
  const noUIOptions = useRef<
    CreateMediaSFURoomOptions | JoinMediaSFURoomOptions | undefined
  >(undefined);

  try {
    if (action === "create") {
      // Prepare parameters for creating a room
      noUIOptions.current = {
        action: "create",
        duration: duration || 15,
        capacity: capacity || 5,
        userName: name,
        eventType: "webinar",
      };
    } else if (action === "join") {
      if (!meetingID) {
        throw new Error("Meeting ID is required for joining a room.");
      }

      // Prepare parameters for joining a room
      noUIOptions.current = {
        action: "join",
        userName: name,
        meetingID,
      };
    } else {
      throw new Error('Invalid action. Must be either "create" or "join".');
    }
  } catch (error) {
    console.error("Error handling MediaSFU action:", error);
  }

  return (
   <div style={{ width: 0, height: 0, maxHeight: 0, maxWidth: 0, overflow: "hidden" }}>
    <MediasfuGeneric
      PrejoinPage={PreJoinPage}
      localLink={localLink.current}
      connectMediaSFU={false}
      returnUI={false}
      noUIPreJoinOptions={noUIOptions.current}
      sourceParameters={sourceParameters}
      updateSourceParameters={updateSourceParameters} 
    />
    </div>
  );
};

export default MediaSFUHandler;

// mediasfu_angular/src/app/components/media-sfu-handler-components/media-sfu-handler.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { MediasfuGeneric, PreJoinPage, Credentials, CreateMediaSFURoomOptions, CreateJoinRoomError, CreateJoinRoomResponse, CreateJoinRoomType, JoinMediaSFURoomOptions } from 'mediasfu-angular';
import { CommonModule } from '@angular/common';

export interface MediaSFUHandlerOptions {
  action: 'create' | 'join';
  duration?: number | null;
  capacity?: number | null;
  name: string;
  meetingID?: string | null;
  sourceParameters: Record<string, any>;
  updateSourceParameters: (params: Record<string, any>) => void;
}

@Component({
  selector: 'app-media-sfu-handler',
  templateUrl: './media-sfu-handler.component.html',
  imports: [CommonModule, MediasfuGeneric],
})

export class MediaSfuHandlerComponent implements OnInit {
  constructor() { }
  @Input() options!: MediaSFUHandlerOptions; // add this line
  noUIOptions = new BehaviorSubject<Partial<MediaSFUHandlerOptions>>({});
  localLink = new BehaviorSubject<string>('http://localhost:3000');
  finalOptions = new BehaviorSubject<CreateMediaSFURoomOptions | JoinMediaSFURoomOptions | null>(null);

  PreJoinPage = PreJoinPage;

  ngOnInit(): void {
    try {
      if (this.options.action === 'create') {
        this.finalOptions.next({
          action: 'create',
          duration: this.options.duration || 15,
          capacity: this.options.capacity || 5,
          userName: this.options.name,
          eventType: 'webinar',
        });
        this.noUIOptions.next(this.options);
      } else if (this.options.action === 'join') {
        if (!this.options.meetingID) {
          throw new Error('Meeting ID is required for joining a room.');
        }
        this.finalOptions.next({
          action: 'join',
          userName: this.options.name,
          meetingID: this.options.meetingID,
        });
        this.noUIOptions.next(this.options);
      } else {
        throw new Error('Invalid action. Must be either "create" or "join".');
      }
    } catch (error) {
      console.error('Error configuring MediaSFU options:', error);
    }
  }
}

<div *ngIf="noUIOptions | async as options" style="width: 0; height: 0; max-height: 0; max-width: 0; overflow: hidden">
  <app-mediasfu-generic
  [PrejoinPage]="PreJoinPage"
  [sourceParameters]="options.sourceParameters"
  [updateSourceParameters]="options.updateSourceParameters"
  [noUIPreJoinOptions]="finalOptions.value!"
  [localLink]="localLink.value"
  [connectMediaSFU]="false"
  [returnUI]="false"
  ></app-mediasfu-generic>
</div>
