// mediasfu_reactjs/src/components/AudioLevelBars.tsx
import { useState, useEffect } from "react";

const AudioLevelBars: React.FC<{ audioLevel: number }> = ({ audioLevel }) => {
    const [level, setLevel] = useState(0);
  
    useEffect(() => {
      // Smoothly animate the audio level
      const animation = setInterval(() => {
        setLevel((prev) => {
          if (prev === audioLevel) return prev;
          return prev < audioLevel
            ? Math.min(prev + 5, audioLevel) // Increment
            : Math.max(prev - 5, audioLevel); // Decrement
        });
      }, 50);
  
      return () => clearInterval(animation);
    }, [audioLevel]);
  
    // Normalize the audio level to determine the number of filled bars
    const normalizedLevel = Math.max(0, ((level - 127.5) / (275 - 127.5)) * 10); // Map to 0–10 bars
    const bars = Array.from({ length: 10 }, (_, i) => i < normalizedLevel);
  
    return (
      <div className="audio-bars-container">
        {bars.map((filled, index) => (
          <div
            key={index}
            className={`audio-bar ${filled ? "filled" : ""}`}
            style={{
              backgroundColor: filled
                ? `rgb(${255 - index * 20}, ${index * 20}, 0)` // Heatmap gradient
                : "#ccc",
            }}
          ></div>
        ))}
      </div>
    );
  };

export default AudioLevelBars;

// mediasfu_angular/src/app/components/audio-level-bars.components/audio-level-bars.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-audio-level-bars',
  templateUrl: './audio-level-bars.component.html',
  styleUrls: ['./audio-level-bars.component.css'],
  imports: [CommonModule]
})
export class AudioLevelBarsComponent implements OnChanges {
  @Input() audioLevel: number = 0;
  bars: boolean[] = Array(10).fill(false);

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['audioLevel']) {
      this.updateBars();
    }
  }

  private updateBars(): void {
    const normalizedLevel = Math.max(
      0,
      ((this.audioLevel - 127.5) / (275 - 127.5)) * 10
    ); // Normalize audio level to 0–10
    this.bars = this.bars.map((_, index) => index < normalizedLevel);
  }

  getColor(index: number): string {
    // Example: Generate a heatmap gradient from red to green
    const red = Math.max(255 - index * 20, 0); // Decrease red as index increases
    const green = Math.min(index * 20, 255);   // Increase green as index increases
    return `rgb(${red}, ${green}, 0)`;         // Return RGB color
  }

}

<div class="audio-bars-container">
  <div
    *ngFor="let filled of bars; let i = index"
    class="audio-bar"
    [class.filled]="filled"
    [style.background-color]="filled ? getColor(i) : '#ccc'"
  ></div>
</div>
